// Local test
POST http://localhost:3000/product/create-product HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQHNtYXJ0bWFydC5jb20iLCJleHAiOjE2NzM4Nzc3NTA5NjMsInVzZXJUeXBlIjoiQWRtaW4iLCJpYXQiOjE2NzM3Nzc3NTB9.VIdLiyLRT8Jbef_5WT69Hc0GPp7aVT0GgYPB3JwFo1U

{
    
}
