"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      "Products",
      [
        {
          id: 1,
          product_name: "Zubits",
          product_alt_text: "Magnetic shoe laces",
          product_price: "4.99€",
          product_description:
            "Never tie your shoe laces again! These magnetic shoelaces...",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 2,
          product_name: "Orange Pi 5 4GB",
          product_alt_text: "Raspberry pi alternative",
          product_price: "4.99€",
          product_description: "description lorem...",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 3,
          product_name: "Ecoco, Automatic Toothpaste Dispenser",
          product_alt_text: "Wall mounted toothpaste dispenser",
          product_price: "9.99€",
          product_description: "description lorem ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 4,
          product_name: "Life Straw",
          product_alt_text:
            "Straw that converts any unpurified water into drinkable water.",
          product_price: "2.99€",
          product_description: "description lorem ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 5,
          product_name: "Sushi Roller",
          product_alt_text: "Sushi Roller that automates sushi making.",
          product_price: "12.99€",
          product_description: "description lorem ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 6,
          product_name: "Cable Manager",
          product_alt_text: "",
          product_price: "12.99€",
          product_description: "description lorem ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 7,
          product_name: "Unit cable clips",
          product_alt_text: "",
          product_price: "12.99€",
          product_description: "description lorem ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 8,
          product_name: "L-Theanine",
          product_alt_text:
            "Naturally occurring amino acid found in tea, studies have shown that taking 200 mg of L-theanine has a calming effect, without causing drowsiness.",
          product_price: "12.99€",
          product_description: "description lorem ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 9,
          product_name: "Smart plug",
          product_alt_text: "",
          product_price: "12.99€",
          product_description: "Program your plugs, save money ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 10,
          product_name: "Creatine Monohydrate",
          product_alt_text: "Good for workouts or something, will change this",
          product_price: "12.99€",
          product_description: "Program your plugs, save money ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 11,
          product_name: "Panax Ginseng",
          product_alt_text: "Boost",
          product_price: "12.99€",
          product_description: "Boost brain function ",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 12,
          product_name: "Toothbrush Holder",
          product_alt_text: "Boost",
          product_price: "12.99€",
          product_description: "Also doubles as a bathroom clip.",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 13,
          product_name: "Cleaning slippers",
          product_alt_text: "Turn your house guests into cleaning serfs.",
          product_price: "12.99€",
          product_description: "",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 14,
          product_name: "Silicone washing gloves",
          product_alt_text: "",
          product_price: "12.99€",
          product_description: "Holding sponges no more",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 15,
          product_name: "Smart light bulb",
          product_alt_text: "",
          product_price: "12.99€",
          product_description: "smart lightbulb",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 16,
          product_name: "Smart switch",
          product_alt_text: "",
          product_price: "12.99€",
          product_description: "smart switch",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 17,
          product_name: "Caffeine tablets",
          product_alt_text: "caf tablets",
          product_price: "12.99€",
          product_description: "caf tablets",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 18,
          product_name: "Smart thermostat handler",
          product_alt_text: "",
          product_price: "12.99€",
          product_description: "Smart thermostat handler",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 19,
          product_name: "Backup Battery",
          product_alt_text: "Uninteruptable electricity backup",
          product_price: "12.99€",
          product_description: "Uninteruptable electricity backup",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
        {
          id: 20,
          product_name: "Dreame D9 Pro: Valetudo custom firmware",
          product_alt_text:
            "State of the art cleaning robot unlinked from the public cloud",
          product_price: "12.99€",
          product_description: "Uninteruptable electricity backup",
          active: true,
          createdAt: Sequelize.literal("CURRENT_TIMESTAMP"),
          updatedAt: Sequelize.literal("CURRENT_TIMESTAMP"),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete("Products", null, {});
  },
};
